import LegalLayout, { prose } from '@/components/legal/LegalLayout'

export const metadata = {
  title: 'Terms of Service — Methea',
  description: 'The terms that govern your use of Methea.',
}

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="27 July 2026">
      <p style={prose.p}>
        These terms govern your use of Methea, operated by Bermet Koshoeva, a sole proprietor
        (ИП / individual entrepreneur) registered in the Kyrgyz Republic (&quot;we&quot;,
        &quot;us&quot;). By creating an account or using Methea, you agree to these terms. If you
        have questions, contact us at <a href="mailto:privacy@methea.app">privacy@methea.app</a>.
      </p>

      <section style={prose.section}>
        <h2 style={prose.h2}>1. Academic integrity — what Methea is and isn&apos;t</h2>
        <p style={prose.p}>
          Methea is a <strong style={prose.strong}>process tool, not an output tool</strong>. It
          helps you structure your thinking — theoretical framework, methodology, research
          instruments, and analysis — but it does not write your research for you.
        </p>
        <p style={prose.p}>
          <strong style={prose.strong}>You are the author of your research.</strong> Any
          methodology scaffold, framework narrative, interview guide, or other output Methea
          generates is a starting point for your own thinking and writing, not finished academic
          work. Text generated by Methea (including any &quot;polished draft&quot; option) must be
          reviewed, edited, and put into your own words before it is submitted as your own work.
          You are solely responsible for ensuring your submission complies with your
          institution&apos;s academic integrity, plagiarism, and AI-use policies.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>2. Acceptable use</h2>
        <ul style={prose.list}>
          <li style={prose.listItem}><span style={prose.dot}>—</span>Don&apos;t use Methea to generate content you intend to submit as your own unedited academic work.</li>
          <li style={prose.listItem}><span style={prose.dot}>—</span>Don&apos;t upload content you don&apos;t have the right to upload (e.g. interview transcripts without appropriate consent — see our Privacy Policy, section 6).</li>
          <li style={prose.listItem}><span style={prose.dot}>—</span>Don&apos;t attempt to disrupt, reverse-engineer, or gain unauthorised access to the service or other users&apos; data.</li>
          <li style={prose.listItem}><span style={prose.dot}>—</span>Don&apos;t use Methea for any unlawful purpose, or in a way that infringes anyone else&apos;s rights.</li>
        </ul>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>3. Account terms</h2>
        <p style={prose.p}>
          You need an account to use Methea. You&apos;re responsible for keeping your login
          credentials secure and for all activity under your account. You must provide accurate
          information when creating your account. We may suspend or terminate accounts that violate
          these terms or the acceptable use rules above.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>4. Purchases and payments</h2>
        <p style={prose.p}>
          Methea&apos;s paid plan is <strong style={prose.strong}>$49 per project, one-time</strong>,
          covering that project until it&apos;s complete. Other plans, if and when offered, will be
          described at the point of purchase.
        </p>
        <p style={prose.p}>
          Payments are processed by <strong style={prose.strong}>Paddle.com Market Limited</strong>,
          who acts as the <strong style={prose.strong}>merchant of record</strong> for your
          purchase. Paddle — not Methea — bills you, handles VAT and applicable sales tax, issues
          invoices and receipts, and processes refunds. Your contract for the purchase itself is
          with Paddle as reseller; these Terms govern your use of the Methea service that purchase
          unlocks.
        </p>
        <p style={prose.p}>
          <strong style={prose.strong}>Right of withdrawal (EU/UK consumers).</strong> If
          you&apos;re a consumer in the EU or UK, you generally have a 14-day right to withdraw from
          a distance purchase of digital content. Because Methea is a digital service delivered
          immediately on payment, <strong style={prose.strong}>starting to use the paid features
          before the 14-day period ends may waive this right</strong>, where you have expressly
          requested early access and acknowledged that you lose the withdrawal right by doing so.
          Refund requests are handled by Paddle in line with their refund policy and applicable
          law.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>5. Intellectual property and ownership</h2>
        <p style={prose.p}>
          <strong style={prose.strong}>Your research content is yours.</strong> You own your topic,
          research question, framework selections, methodology, interview guides, transcripts, and
          any findings or analysis generated from your work in Methea.
        </p>
        <p style={prose.p}>
          <strong style={prose.strong}>Methea owns the platform.</strong> This includes the Methea
          software, product design, and our curated theory library (the set of theoretical
          frameworks, summaries, and citations we maintain and verify). You may use the theory
          library within the service to build your own research, but the library itself, and the
          Methea platform, remain our property and may not be copied, scraped, or redistributed.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>6. Disclaimers and limitation of liability</h2>
        <p style={prose.p}>
          Methea is provided &quot;as is,&quot; without warranties of any kind, to the fullest
          extent permitted by law. Methea is a structuring and drafting-assistance tool — it does
          not guarantee academic outcomes, grades, ethics/IRB approval, or that any suggested
          theory, framework, or methodology is correct or appropriate for your specific research.
          You remain responsible for the academic and methodological soundness of your own
          research.
        </p>
        <p style={prose.p}>
          To the fullest extent permitted by law, we are not liable for any indirect, incidental,
          or consequential damages arising from your use of Methea, including academic outcomes.
          Our total liability for any claim relating to the service is limited to the amount you
          paid us for the project giving rise to the claim.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>7. Changes to these terms</h2>
        <p style={prose.p}>
          We may update these terms as the product evolves. We will update the &quot;last
          updated&quot; date above and, for material changes, notify you.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>8. Governing law</h2>
        <p style={prose.p}>
          These terms are governed by the laws of the Kyrgyz Republic, without regard to conflict
          of law principles, and without limiting any mandatory consumer-protection rights you have
          under the law of your own country of residence.
        </p>
      </section>

      <section style={prose.section}>
        <h2 style={prose.h2}>9. Contact</h2>
        <p style={prose.p}>
          Questions about these terms: <a href="mailto:privacy@methea.app">privacy@methea.app</a>
        </p>
      </section>
    </LegalLayout>
  )
}
